/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_emont;

import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.*;
import javax.swing.JFrame;
import javax.swing.table.*;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import java.text.NumberFormat;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.text.SimpleDateFormat;
import java.util.Calendar;


/**
 *
 * @author Naufal Ghani
 */
public class menuUtama extends javax.swing.JFrame {
    private ArrayList<String> listKebutuhan = new ArrayList<>();

    
    public menuUtama() {
        initComponents();
        
    }
    
    public void reset(){
        txt_keterangan.setText(null);
        txt_persentase.setText(null);
    }
    
    private void updateComboBoxFromTable() {
        // Bersihkan ComboBox sebelum menambahkan data baru
        cb_keterangan.removeAllItems();

        // Ambil model dari tabel
        DefaultTableModel tableModel = (DefaultTableModel) tabel_mc.getModel();

        // Iterasi setiap baris di tabel
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            // Ambil nilai dari kolom pertama
            String item = tableModel.getValueAt(i, 0).toString();

            // Tambahkan ke ComboBox
            cb_keterangan.addItem(item);
        }
        cb_keterangan.addItem("Dana Darurat");
    }

    
    DefaultTableModel model;    
    
    /**
     * Creates new form menuUtama
     */



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btng_laporan = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        btnMonthlyCycle = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnRecap = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnDaily = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnAboutUs = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        recapPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_recap = new javax.swing.JTable();
        btn_deleterecap = new javax.swing.JButton();
        field_saldorecap = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        dailyPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_nominal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_tanggal = new com.toedter.calendar.JDateChooser();
        cb_keterangan = new javax.swing.JComboBox<>();
        btn_dailybudget = new javax.swing.JButton();
        btn_pemasukan = new javax.swing.JRadioButton();
        btn_pengeluaran = new javax.swing.JRadioButton();
        monthlyPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_uangbulanan = new javax.swing.JTextField();
        txt_persentase = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btn_AllKebutuhan = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_keterangan = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel_mc = new javax.swing.JTable();
        field_uangbulanan = new javax.swing.JLabel();
        btn_delete = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        txt_danadarurat = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EMONT _ Application");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));

        menuPanel.setBackground(new java.awt.Color(0, 153, 0));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_emont/LOGO EMONT-01.png"))); // NOI18N
        logo.setFocusCycleRoot(true);
        logo.setMaximumSize(new java.awt.Dimension(20, 20));
        logo.setMinimumSize(new java.awt.Dimension(20, 20));
        logo.setPreferredSize(new java.awt.Dimension(20, 20));

        btnMonthlyCycle.setBackground(new java.awt.Color(0, 102, 0));
        btnMonthlyCycle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMonthlyCycle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMonthlyCycleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMonthlyCycleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMonthlyCycleMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMonthlyCycleMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMonthlyCycleMouseReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dinofiles", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MONTHLY CYCLE");

        javax.swing.GroupLayout btnMonthlyCycleLayout = new javax.swing.GroupLayout(btnMonthlyCycle);
        btnMonthlyCycle.setLayout(btnMonthlyCycleLayout);
        btnMonthlyCycleLayout.setHorizontalGroup(
            btnMonthlyCycleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMonthlyCycleLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel3)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        btnMonthlyCycleLayout.setVerticalGroup(
            btnMonthlyCycleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMonthlyCycleLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        btnRecap.setBackground(new java.awt.Color(0, 102, 0));
        btnRecap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRecap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRecapMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRecapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRecapMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRecapMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnRecapMouseReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dinofiles", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("recapitulation");

        javax.swing.GroupLayout btnRecapLayout = new javax.swing.GroupLayout(btnRecap);
        btnRecap.setLayout(btnRecapLayout);
        btnRecapLayout.setHorizontalGroup(
            btnRecapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRecapLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel10)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        btnRecapLayout.setVerticalGroup(
            btnRecapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnRecapLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        btnDaily.setBackground(new java.awt.Color(0, 102, 0));
        btnDaily.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDaily.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDailyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDailyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDailyMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDailyMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDailyMouseReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dinofiles", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("daily budgeting");

        javax.swing.GroupLayout btnDailyLayout = new javax.swing.GroupLayout(btnDaily);
        btnDaily.setLayout(btnDailyLayout);
        btnDailyLayout.setHorizontalGroup(
            btnDailyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDailyLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel11)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        btnDailyLayout.setVerticalGroup(
            btnDailyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDailyLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        btnAboutUs.setBackground(new java.awt.Color(0, 102, 0));
        btnAboutUs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAboutUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAboutUsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAboutUsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAboutUsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAboutUsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAboutUsMouseReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dinofiles", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("about us");

        javax.swing.GroupLayout btnAboutUsLayout = new javax.swing.GroupLayout(btnAboutUs);
        btnAboutUs.setLayout(btnAboutUsLayout);
        btnAboutUsLayout.setHorizontalGroup(
            btnAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAboutUsLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnAboutUsLayout.setVerticalGroup(
            btnAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAboutUsLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnMonthlyCycle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRecap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDaily, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAboutUs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnMonthlyCycle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnRecap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDaily, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAboutUs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        headerPanel.setBackground(new java.awt.Color(204, 255, 102));

        jLabel1.setFont(new java.awt.Font("Humnst777 Blk BT", 1, 72)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setText("EMONT");

        jLabel2.setFont(new java.awt.Font("Humnst777 Blk BT", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 0));
        jLabel2.setText("[ EFFECTIVELY MONEY MANAGEMENT ]");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        mainPanel.setLayout(new java.awt.CardLayout());

        recapPanel.setBackground(new java.awt.Color(153, 255, 153));

        jLabel8.setFont(new java.awt.Font("Dinofiles", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 51));
        jLabel8.setText("recapitulation");

        tabel_recap.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tabel_recap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Pemasukan", "Pengeluaran", "Saldo", "Keterangan", "Tanggal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabel_recap);

        btn_deleterecap.setText("Delete");
        btn_deleterecap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleterecapActionPerformed(evt);
            }
        });

        field_saldorecap.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        field_saldorecap.setForeground(new java.awt.Color(0, 102, 0));
        field_saldorecap.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel24.setFont(new java.awt.Font("Dinofiles", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 51));
        jLabel24.setText("Saldo");

        javax.swing.GroupLayout recapPanelLayout = new javax.swing.GroupLayout(recapPanel);
        recapPanel.setLayout(recapPanelLayout);
        recapPanelLayout.setHorizontalGroup(
            recapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recapPanelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(recapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recapPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(196, 196, 196))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recapPanelLayout.createSequentialGroup()
                        .addGroup(recapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_deleterecap)
                            .addGroup(recapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(recapPanelLayout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(field_saldorecap, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(15, 15, 15))))
        );
        recapPanelLayout.setVerticalGroup(
            recapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recapPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(recapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(field_saldorecap, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_deleterecap)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        mainPanel.add(recapPanel, "card3");

        dailyPanel.setBackground(new java.awt.Color(153, 255, 153));

        jLabel9.setFont(new java.awt.Font("Dinofiles", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 51));
        jLabel9.setText("daily budget");

        jLabel16.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 51));
        jLabel16.setText("Ada Laporan Apa Hari Ini?");

        jLabel17.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 51));
        jLabel17.setText("Keterangan ");

        jLabel18.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 51));
        jLabel18.setText("Laporan");

        jLabel19.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 51));
        jLabel19.setText("Tanggal");

        jLabel20.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 102, 51));
        jLabel20.setText("Nominal");

        txt_nominal.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 153), new java.awt.Color(0, 102, 51)));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Rp.");

        txt_tanggal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txt_tanggalPropertyChange(evt);
            }
        });

        btn_dailybudget.setText("Add");
        btn_dailybudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dailybudgetActionPerformed(evt);
            }
        });

        btng_laporan.add(btn_pemasukan);
        btn_pemasukan.setText("Pemasukan");

        btng_laporan.add(btn_pengeluaran);
        btn_pengeluaran.setText("Pengeluaran");

        javax.swing.GroupLayout dailyPanelLayout = new javax.swing.GroupLayout(dailyPanel);
        dailyPanel.setLayout(dailyPanelLayout);
        dailyPanelLayout.setHorizontalGroup(
            dailyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dailyPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(216, 216, 216))
            .addGroup(dailyPanelLayout.createSequentialGroup()
                .addGroup(dailyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dailyPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dailyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dailyPanelLayout.createSequentialGroup()
                            .addContainerGap(80, Short.MAX_VALUE)
                            .addGroup(dailyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(dailyPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_nominal, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(dailyPanelLayout.createSequentialGroup()
                                    .addGroup(dailyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(dailyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(90, 90, 90)
                                    .addGroup(dailyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(dailyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txt_tanggal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                            .addComponent(cb_keterangan, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(dailyPanelLayout.createSequentialGroup()
                                            .addComponent(btn_pemasukan)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btn_pengeluaran))))))
                        .addGroup(dailyPanelLayout.createSequentialGroup()
                            .addGap(67, 67, 67)
                            .addComponent(btn_dailybudget, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25))
        );
        dailyPanelLayout.setVerticalGroup(
            dailyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dailyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dailyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dailyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pemasukan)
                    .addComponent(btn_pengeluaran))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dailyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tanggal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dailyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nominal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_dailybudget, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(451, Short.MAX_VALUE))
        );

        dailyPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txt_nominal, txt_tanggal});

        mainPanel.add(dailyPanel, "card4");

        monthlyPanel.setBackground(new java.awt.Color(153, 255, 153));

        jLabel7.setFont(new java.awt.Font("Dinofiles", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 51));
        jLabel7.setText("monthly cycle");

        jLabel4.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel4.setText("Siklus ini akan berulang selama sebulan, maka ulangi mengisi tabel ini tiap bulannya.");

        jLabel13.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel13.setText("Masukkan Jumlah Uang Bulananmu");

        txt_persentase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_persentaseActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Rp.");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("%");

        btn_AllKebutuhan.setText("Add");
        btn_AllKebutuhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AllKebutuhanActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel21.setText("Persentase");

        jLabel22.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel22.setText("Keterangan Kebutuhan");

        txt_keterangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_keteranganActionPerformed(evt);
            }
        });

        tabel_mc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kebutuhan", "Persentase", "Total"
            }
        ));
        jScrollPane3.setViewportView(tabel_mc);

        field_uangbulanan.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        field_uangbulanan.setForeground(new java.awt.Color(0, 102, 0));
        field_uangbulanan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel23.setText("Dana Darurat");

        javax.swing.GroupLayout monthlyPanelLayout = new javax.swing.GroupLayout(monthlyPanel);
        monthlyPanel.setLayout(monthlyPanelLayout);
        monthlyPanelLayout.setHorizontalGroup(
            monthlyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, monthlyPanelLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(monthlyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, monthlyPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(196, 196, 196))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, monthlyPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
            .addGroup(monthlyPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(monthlyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(field_uangbulanan, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(monthlyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(monthlyPanelLayout.createSequentialGroup()
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                            .addComponent(txt_danadarurat, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(monthlyPanelLayout.createSequentialGroup()
                            .addComponent(btn_AllKebutuhan, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(monthlyPanelLayout.createSequentialGroup()
                            .addGroup(monthlyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(81, 81, 81)
                            .addGroup(monthlyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_keterangan)
                                .addGroup(monthlyPanelLayout.createSequentialGroup()
                                    .addComponent(txt_persentase, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel14))))
                        .addComponent(jScrollPane3)
                        .addGroup(monthlyPanelLayout.createSequentialGroup()
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel6)
                            .addGap(12, 12, 12)
                            .addComponent(txt_uangbulanan))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        monthlyPanelLayout.setVerticalGroup(
            monthlyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monthlyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(monthlyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_uangbulanan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(monthlyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(monthlyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_persentase, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(monthlyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_AllKebutuhan, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addComponent(field_uangbulanan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(monthlyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(monthlyPanelLayout.createSequentialGroup()
                        .addComponent(txt_danadarurat)
                        .addGap(5, 5, 5)))
                .addGap(130, 130, 130))
        );

        mainPanel.add(monthlyPanel, "card2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMonthlyCycleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMonthlyCycleMouseEntered
        btnMonthlyCycle.setBackground(new Color(153,255,153));
    }//GEN-LAST:event_btnMonthlyCycleMouseEntered

    private void btnMonthlyCycleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMonthlyCycleMouseExited
        btnMonthlyCycle.setBackground(new Color(153,255,153));
    }//GEN-LAST:event_btnMonthlyCycleMouseExited

    private void btnMonthlyCycleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMonthlyCycleMousePressed
        btnMonthlyCycle.setBackground(new Color(153,255,153));
    }//GEN-LAST:event_btnMonthlyCycleMousePressed

    private void btnMonthlyCycleMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMonthlyCycleMouseReleased
        btnMonthlyCycle.setBackground(new Color(153,255,153));
    }//GEN-LAST:event_btnMonthlyCycleMouseReleased

    private void btnMonthlyCycleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMonthlyCycleMouseClicked
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(monthlyPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnMonthlyCycleMouseClicked

    private void btnRecapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecapMouseClicked
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(recapPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnRecapMouseClicked

    private void btnRecapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecapMouseEntered
        // TODO add your handling code here:
        btnRecap.setBackground(new Color(153,255,153));
    }//GEN-LAST:event_btnRecapMouseEntered

    private void btnRecapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecapMouseExited
        // TODO add your handling code here:
        btnRecap.setBackground(new Color (255,102,102));
    }//GEN-LAST:event_btnRecapMouseExited

    private void btnRecapMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecapMousePressed
        // TODO add your handling code here:
        btnRecap.setBackground(new Color(153,255,153));
    }//GEN-LAST:event_btnRecapMousePressed

    private void btnRecapMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecapMouseReleased
        // TODO add your handling code here:
        btnRecap.setBackground(new Color (255,102,102));
    }//GEN-LAST:event_btnRecapMouseReleased

    private void btnDailyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDailyMouseClicked
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(dailyPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnDailyMouseClicked

    private void btnDailyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDailyMouseEntered
        // TODO add your handling code here:
        btnDaily.setBackground(new Color(153,255,153));
    }//GEN-LAST:event_btnDailyMouseEntered

    private void btnDailyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDailyMouseExited
        // TODO add your handling code here:
        btnDaily.setBackground(new Color (255,102,102));
    }//GEN-LAST:event_btnDailyMouseExited

    private void btnDailyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDailyMousePressed
        // TODO add your handling code here:
        btnDaily.setBackground(new Color(153,255,153));
    }//GEN-LAST:event_btnDailyMousePressed

    private void btnDailyMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDailyMouseReleased
        // TODO add your handling code here:
        btnDaily.setBackground(new Color (255,102,102));
    }//GEN-LAST:event_btnDailyMouseReleased

    private void btnAboutUsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutUsMouseClicked
        // TODO add your handling code here:
        About x = new About();
        x.setVisible(true);
    }//GEN-LAST:event_btnAboutUsMouseClicked

    private void btnAboutUsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutUsMouseEntered
        // TODO add your handling code here:
        btnAboutUs.setBackground(new Color (153,255,153));
    }//GEN-LAST:event_btnAboutUsMouseEntered

    private void btnAboutUsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutUsMouseExited
        // TODO add your handling code here:
        btnAboutUs.setBackground(new Color (255,102,102));
    }//GEN-LAST:event_btnAboutUsMouseExited

    private void btnAboutUsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutUsMousePressed
        // TODO add your handling code here:
        btnAboutUs.setBackground(new Color (153,255,153));
    }//GEN-LAST:event_btnAboutUsMousePressed

    private void btnAboutUsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutUsMouseReleased
        // TODO add your handling code here:
        btnAboutUs.setBackground(new Color (255,102,102));
    }//GEN-LAST:event_btnAboutUsMouseReleased

    private void txt_persentaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_persentaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_persentaseActionPerformed

    private void txt_tanggalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txt_tanggalPropertyChange
        
    }//GEN-LAST:event_txt_tanggalPropertyChange

    private void txt_keteranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_keteranganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_keteranganActionPerformed

    private void btn_AllKebutuhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AllKebutuhanActionPerformed
        // TODO add your handling code here:
        try {
        double persen, uang, totalpersen;
        double totalPengeluaran = 0; // Untuk mengakumulasi total pengeluaran
        double sisaDanaDarurat; // Variabel untuk dana darurat

        // Ambil input user
        persen = Double.parseDouble(txt_persentase.getText());
        uang = Double.parseDouble(txt_uangbulanan.getText());

        // Hitung pengeluaran berdasarkan persentase
        totalpersen = (persen / 100) * uang;

        DefaultTableModel m = (DefaultTableModel) tabel_mc.getModel();

        // Validasi input
        if (txt_uangbulanan.getText().trim().equals("") ||
            txt_keterangan.getText().trim().equals("") ||
            txt_persentase.getText().trim().equals("")) {

            JOptionPane.showMessageDialog(null, "Data yang anda masukkan belum lengkap\nSilahkan ulangi lagi");
        } else {
            // Akumulasi total pengeluaran dari tabel (hitung sebelumnya)
            totalPengeluaran = 0;
            for (int i = 0; i < m.getRowCount(); i++) {
                String totalStr = m.getValueAt(i, 2).toString().replace("Rp. ", "");
                totalPengeluaran += Double.parseDouble(totalStr);
            }

            // Cek jika menambahkan data akan melebihi batas uang bulanan
            if ((totalPengeluaran + totalpersen) > uang) {
                JOptionPane.showMessageDialog(null, 
                    "Peringatan: Total pengeluaran melebihi batas uang bulanan!\nSilakan periksa kembali input Anda.",
                    "Batas Uang Terlampaui", JOptionPane.WARNING_MESSAGE);
            } else {
                // Tambahkan data ke tabel jika belum melebihi batas
                m.addRow(new Object[]{
                    txt_keterangan.getText(), // Keterangan
                    txt_persentase.getText() + "%", // Persentase
                    "Rp. " + totalpersen // Total pengeluaran berdasarkan persentase
                });

                // Hitung ulang total pengeluaran setelah input valid
                totalPengeluaran += totalpersen;

                // Hitung sisa dana darurat
                sisaDanaDarurat = uang - totalPengeluaran;

                // Tampilkan dana darurat di textfield
                txt_danadarurat.setText("Rp. " + String.format("%.2f", sisaDanaDarurat));

                // Reset input fields
                reset();
                
                updateComboBoxFromTable();

                // Tampilkan uang bulanan
                field_uangbulanan.setText("Rp. " + String.format("%.2f", uang));
            }

            // Tambahkan keterangan ke list dan ComboBox (hindari duplikasi)
            String kebutuhan = txt_keterangan.getText();
           
            listKebutuhan.add(kebutuhan);
            cb_keterangan.addItem(kebutuhan); // Tambahkan langsung ke ComboBox
            
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Silakan masukkan angka yang valid!");
    }        
        
 
    }//GEN-LAST:event_btn_AllKebutuhanActionPerformed

    private void btn_dailybudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dailybudgetActionPerformed
        // TODO add your handling code here:
        
        try {
            // Ambil nilai dari ComboBox
            String keterangan = cb_keterangan.getSelectedItem().toString();

            // Ambil nilai dari ButtonGroup (Pemasukan atau Pengeluaran)
            String jenis;
            if (btn_pemasukan.isSelected()) {
                jenis = "Pemasukan";
            } else if (btn_pengeluaran.isSelected()) {
                jenis = "Pengeluaran";
            } else {
                JOptionPane.showMessageDialog(null, "Silakan pilih jenis pemasukan atau pengeluaran.");
                return;
            }

            // Ambil tanggal dari JDateChooser
            if (txt_tanggal.getDate() == null) {
                JOptionPane.showMessageDialog(null, "Silakan pilih tanggal terlebih dahulu.");
                return;
            }
            String tanggal = new SimpleDateFormat("dd-MM-yyyy").format(txt_tanggal.getDate());

            // Ambil nominal dari TextField
            double nominal;
            try {
                nominal = Double.parseDouble(txt_nominal.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Masukkan nominal uang yang valid!");
                return;
            }

            // Ambil model tabel recap
            DefaultTableModel tabelRecap = (DefaultTableModel) tabel_recap.getModel();

//CEK BATAS PENGELUARAN
//=================================================================================

//            // Ambil batas budget dari tabel_mc
//            double batasAnggaran = 0;
//            boolean kategoriDitemukan = false;
//
//            for (int i = 0; i < tabel_mc.getRowCount(); i++) {
//                String kategori = tabel_mc.getValueAt(i, 0).toString(); // Kolom "Keterangan" pada tabel_mc
//                if (kategori.equalsIgnoreCase(keterangan)) {
//                    batasAnggaran = Double.parseDouble(tabel_mc.getValueAt(i, 2).toString()); // Kolom "Total"
//                    kategoriDitemukan = true;
//                    break;
//                }
//            }
//
//            if (!kategoriDitemukan) {
//                JOptionPane.showMessageDialog(null, "Kategori '" + keterangan + "' tidak ditemukan dalam tabel anggaran.");
//                return;
//            }
//
//            // Debug batas anggaran
//            System.out.println("Kategori: " + keterangan + ", Batas Anggaran: " + batasAnggaran);
//
//            // Hitung total pengeluaran kategori di tabel_recap
//            double totalPengeluaranKategori = 0;
//            for (int i = 0; i < tabelRecap.getRowCount(); i++) {
//                if (tabelRecap.getValueAt(i, 4).toString().equalsIgnoreCase(keterangan)) { // Kolom "Keterangan"
//                    if (!tabelRecap.getValueAt(i, 2).toString().equals("0")) { // Kolom "Pengeluaran"
//                        totalPengeluaranKategori += Double.parseDouble(tabelRecap.getValueAt(i, 2).toString());
//                    }
//                }
//            }
//
//            // Debug pengeluaran kategori
//            System.out.println("Total Pengeluaran Kategori (Sebelum): " + totalPengeluaranKategori);
//
//            // Tambahkan nominal baru ke total pengeluaran kategori
//            if (jenis.equals("Pengeluaran")) {
//                totalPengeluaranKategori += nominal;
//
//                // Debug total pengeluaran setelah ditambah nominal baru
//                System.out.println("Total Pengeluaran Kategori (Setelah): " + totalPengeluaranKategori);
//
//                // Cek apakah melebihi batas anggaran
//                if (totalPengeluaranKategori > batasAnggaran) {
//                    JOptionPane.showMessageDialog(null,
//                        "Pengeluaran untuk kategori '" + keterangan + "' telah melebihi batas anggaran!\n" +
//                        "Batas Anggaran: Rp. " + batasAnggaran + "\n" +
//                        "Pengeluaran Saat Ini: Rp. " + totalPengeluaranKategori,
//                        "Peringatan", JOptionPane.WARNING_MESSAGE);
//                }
//            }

//CEK BATAS PENGELUARAN
//=================================================================================

            // Tambahkan nomor baris otomatis
            int nomor = tabelRecap.getRowCount() + 1;

            // Ambil saldo awal dari txt_uangbulanan
            double saldoAwal;
            try {
                saldoAwal = Double.parseDouble(txt_uangbulanan.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Masukkan saldo awal (uang bulanan) yang valid!");
                return;
            }

            // Hitung saldo berdasarkan jenis transaksi
            double saldo;
            if (tabelRecap.getRowCount() > 0) {
                // Ambil saldo terakhir dari tabel
                saldo = Double.parseDouble(tabelRecap.getValueAt(tabelRecap.getRowCount() - 1, 3).toString());
            } else {
                // Jika tabel kosong, gunakan saldo awal
                saldo = saldoAwal;
            }

            if (jenis.equals("Pemasukan")) {
                saldo += nominal;
            } else if (jenis.equals("Pengeluaran")) {
                saldo -= nominal;
            }

            // Tambahkan data ke tabel
            tabelRecap.addRow(new Object[]{
                nomor,                                         // Kolom No
                jenis.equals("Pemasukan") ? nominal : 0,       // Kolom Pemasukan
                jenis.equals("Pengeluaran") ? nominal : 0,     // Kolom Pengeluaran
                saldo,                                         // Kolom Saldo
                keterangan,                                    // Kolom Keterangan
                tanggal                                        // Kolom Tanggal
            });

            // Tampilkan saldo terakhir di field_saldorecap
            field_saldorecap.setText(String.format("Rp. " + "%.2f", saldo));

            // Reset input field
            cb_keterangan.setSelectedIndex(0);
            btng_laporan.clearSelection(); // Reset pilihan button group
            txt_tanggal.setDate(null);
            txt_nominal.setText("");

            JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan ke tabel!");
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_dailybudgetActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel) tabel_mc.getModel();

        // Ambil baris yang dipilih
        int selectedRow = tabel_mc.getSelectedRow();

        // Periksa apakah ada baris yang dipilih
        if (selectedRow != -1) {
            // Konfirmasi penghapusan
            int confirm = JOptionPane.showConfirmDialog(null, 
                "Apakah Anda yakin ingin menghapus baris ini?", 
                "Konfirmasi Hapus", 
                JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                // Hapus baris yang dipilih
                tableModel.removeRow(selectedRow);

                // Perbarui ComboBox agar tetap sinkron
                updateComboBoxFromTable();

                JOptionPane.showMessageDialog(null, "Baris berhasil dihapus.");
            }
        } else {
            // Tampilkan pesan jika tidak ada baris yang dipilih
            JOptionPane.showMessageDialog(null, 
                "Tidak ada baris yang dipilih. Silakan pilih baris terlebih dahulu.",
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_deleterecapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleterecapActionPerformed
        // TODO add your handling code here:
        try {
            // Ambil model tabel
            DefaultTableModel tabelRecap = (DefaultTableModel) tabel_recap.getModel();

            // Cek apakah ada baris yang dipilih
            int selectedRow = tabel_recap.getSelectedRow();
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(null, "Silakan pilih baris yang ingin dihapus.");
                return;
            }

            // Konfirmasi penghapusan
            int confirm = JOptionPane.showConfirmDialog(null, 
                "Apakah Anda yakin ingin menghapus data ini?", 
                "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                // Hapus baris yang dipilih
                tabelRecap.removeRow(selectedRow);

                // Perbarui nomor baris
                for (int i = 0; i < tabelRecap.getRowCount(); i++) {
                    tabelRecap.setValueAt(i + 1, i, 0); // Kolom No (index 0)
                }

                // Perbarui saldo
                double saldo = Double.parseDouble(txt_uangbulanan.getText());
                for (int i = 0; i < tabelRecap.getRowCount(); i++) {
                    double pemasukan = tabelRecap.getValueAt(i, 1).equals("-") ? 0 
                            : Double.parseDouble(tabelRecap.getValueAt(i, 1).toString());
                    double pengeluaran = tabelRecap.getValueAt(i, 2).equals("-") ? 0 
                            : Double.parseDouble(tabelRecap.getValueAt(i, 2).toString());
                    saldo += pemasukan - pengeluaran;

                    // Update saldo pada tabel
                    tabelRecap.setValueAt(saldo, i, 3);
                }

                // Tampilkan saldo terbaru di field_saldorecap
                field_saldorecap.setText("Rp. " + String.format("%.2f", saldo));

                JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_deleterecapActionPerformed

        
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuUtama().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAboutUs;
    private javax.swing.JPanel btnDaily;
    private javax.swing.JPanel btnMonthlyCycle;
    private javax.swing.JPanel btnRecap;
    private javax.swing.JButton btn_AllKebutuhan;
    private javax.swing.JButton btn_dailybudget;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_deleterecap;
    private javax.swing.JRadioButton btn_pemasukan;
    private javax.swing.JRadioButton btn_pengeluaran;
    private javax.swing.ButtonGroup btng_laporan;
    private javax.swing.JComboBox<String> cb_keterangan;
    private javax.swing.JPanel dailyPanel;
    private javax.swing.JLabel field_saldorecap;
    private javax.swing.JLabel field_uangbulanan;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel monthlyPanel;
    private javax.swing.JPanel recapPanel;
    private javax.swing.JTable tabel_mc;
    private javax.swing.JTable tabel_recap;
    private javax.swing.JTextField txt_danadarurat;
    private javax.swing.JTextField txt_keterangan;
    private javax.swing.JTextField txt_nominal;
    private javax.swing.JTextField txt_persentase;
    private com.toedter.calendar.JDateChooser txt_tanggal;
    private javax.swing.JTextField txt_uangbulanan;
    // End of variables declaration//GEN-END:variables

    
    
    

